name: Update RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install poetry via pipx
        run: |
          pip install --user pipx
          pipx ensurepath
          pipx install poetry
      - name: install dependencies
        run: poetry install
      - name: generate rss feed
        run: poetry run python3 generate_rss.py
      - name: Commit RSS feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update RSS feed"
          git push origin master